Shop/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
]

app/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('section/<str:name>/', views.section, name='section'),
    path('storage/<str:name>/', views.storage, name='storage'),
    path('detail/<int:id>/', views.detail, name='detail'),

] 
urlpatterns+=[
        url(r'^media/(?P<path>.*)$',serve,{
            'document_root':settings.MEDIA_ROOT}),
    ]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

app/models.py
from django.db import models

# Create your models here.
class Section(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Product(models.Model):
    section = models.ForeignKey(Section, on_delete = models.CASCADE)
    name = models.CharField(max_length=50)
    price = models.IntegerField(default=0)
    photo = models.ImageField(upload_to='media/', height_field=None, width_field=None, max_length=100,default="")
    count = models.IntegerField(default=0)
    detail = models.CharField(max_length=999,default="")    
    def __str__(self):
        return "Name "+str(self.name)+ "|Price "+str(self.price)+"|Count "+ str(self.count)

class Storage(models.Model):
    product = models.ManyToManyField(Product)
    name = models.CharField(max_length=50)
   
    def __str__(self):
        return self.name

cart/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render,redirect
from app.models import Section,Product,Storage


def index(request):
    products=Product.objects.order_by("?").all()[:5]
    sections=Section.objects.all()
    storages=Storage.objects.all()

    return render(request, 'app/index.html', {'products': products,'sections':sections,'storages':storages})


def section(request, name):
     try:
        sections=Section.objects.get(name=name)
        products=sections.product_set.all()
        return render(request, 'app/section.html', {'products': products})
     except Exception as e:
        return redirect('/')

def storage(request, name):
    try:
        storages=Storage.objects.get(name=name)
        products=storages.product.all()
        return render(request, 'app/storage.html', {'products': products})
    except Exception as e:
        return redirect('/')


def detail(request, id):
    product=Product.objects.filter(id=id)
    
    return render(request, 'app/detail.html', {'product': product})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from app.models import Product
from .cart import Cart




def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product=product)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
   
    return render(request, 'cart/detail.html', {'cart': cart})

app/templates/app/detail.html
{% if product%}
<table border="1">
    {% for c in product %}

        
            <tr>
                <td >
                    <p>Name: {{ c.name }} </p>
                </td>
                <td>
                    <p>Price: {{ c.price }} </p>
                </td>
                <td>
                    <img src= {{ c.photo.url }} height="100" width="100" />
                </td>
                <td>
                    <p>Count: {{ c.count }} </p>
                </td>
                <td>
                    <p><a href="{% url 'cart:cart_add' c.id %}">Add to Cart </a></p>  
                </td>
            </tr>
            <tr>
                <td colspan="5"><p>Detail: {{ c.detail }} </p></td>
            </tr>
  

    {% endfor %}
</table>
{% endif %}
<a href="{% url 'app:index'%}">Back</a>

app/templates/app/index.html
Sections
{% if sections%}
<ul>
    {% for c in sections %}
    <li><a href="{% url 'app:section' c.name %}">{{ c.name }} </a></li>
    {% endfor %}
</ul>
{% endif %}
Storages
{% if storages%}
<ul>
    {% for c in storages %}
    <li><a href="{% url 'app:storage' c.name %}">{{ c.name }} </a></li>
    {% endfor %}
</ul>
{% endif %}
<p><a href="{% url 'cart:cart_detail' %}">My cart </a></p>  
Random 5 products
{% if products%}
<table border="1">
    {% for c in products %}     
            <tr>
                <td >
                    <p>Name: {{ c.name }} </p>
                </td>
                <td>
                    <p>Price: {{ c.price }} </p>
                </td>
                <td>
                    <img src= {{ c.photo.url }} height="100" width="100" />
                </td>
                <td>
                    <p>Count: {{ c.count }} </p>
                </td>
                <td>
                    <p><a href="{% url 'app:detail' c.id %}">Detail </a></p>  
                </td>
                <td>
                    <p><a href="{% url 'cart:cart_add' c.id %}">Add to Cart </a></p>  
                </td>
            </tr>
    {% endfor %}
</table>
{% endif %}

app/templates/app/section.html
{% if products%}
<table border="1">
    {% for c in products %}

        
            <tr>
                <td >
                    <p>Name: {{ c.name }} </p>
                </td>
                <td>
                    <p>Price: {{ c.price }} </p>
                </td>
                <td>
                    <img src= {{ c.photo.url }} height="100" width="100" />
                </td>
                <td>
                    <p>Count: {{ c.count }} </p>
                </td>
                <td>
                    <p><a href="{% url 'app:detail' c.id %}">Detail </a></p>  
                </td>
                <td>
                    <p><a href="{% url 'cart:cart_add' c.id %}">Add to Cart </a></p>  
                </td>
            </tr>
  

    {% endfor %}
</table>
{% endif %}
<br>
<a href="{% url 'app:index'%}">Back</a>

app/templates/app/storage.html
{% if products%}
<table border="1">
    {% for c in products %}

        
            <tr>
                <td >
                    <p>Name: {{ c.name }} </p>
                </td>
                <td>
                    <p>Price: {{ c.price }} </p>
                </td>
                <td>
                    <img src= {{ c.photo.url }} height="100" width="100" />
                </td>
                <td>
                    <p>Count: {{ c.count }} </p>
                </td>
                <td>
                    <p><a href="{% url 'app:detail' c.id %}">Detail </a></p>  
                </td>
                <td>
                    <p><a href="{% url 'cart:cart_add' c.id %}">Add to Cart </a></p>  
                </td>
            </tr>
  

    {% endfor %}
</table>
{% endif %}
<a href="{% url 'app:index'%}">Back</a>

cart/templates/cart/detail.html
  Cart
  <table >
    <thead>
      <tr>
        <th>Product</th>
        <th></th>
        <th></th>
        <th>Count</th>
        <th>Price</th>
        <th>Total price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td><a href="{% url 'app:detail' product.id %}">{{ product.name }} </a></td>

            <td><a href="{% url 'cart:cart_add' product.id %}">Add 1</a></td>

            <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'app:index' %}" class="button light">Back</a>
  </p>